Updating sizing of heading image for Safari Only
thundernest/thunderbird-website pull request #244
Opened 2021-04-05 17:40 UTC by javielico

Updating css rule to the hero image doesn't look squashed on Safari for Mac OSX

[Screenshot of the issue on Safari](https://i.postimg.cc/vDFxVCVn/Screenshot-2021-04-05-at-18-39-14.png)

2021-04-09 05:08 UTC, Sancus commented
@Alecaddd Does this make sense to you? It seems super weird to me that we would need specific code to make Safari display images properly.... I don't have a Mac to test with.

2021-04-10 01:14 UTC, Alecaddd requested changes
Ah yes, the beauty of webkit.

2021-04-10 01:14 UTC, Alecaddd commented on assets/less/base/sizing.less
> +
No need to add the width: 100%, only the height.
Also, please respect the current file indentation.

2021-04-18 16:41 UTC, javielico commented
Changes actioned.

2021-04-18 20:01 UTC, Alecaddd approved these changes

2021-04-21 07:29 UTC, merged