Mission premable and statement
thundernest/thunderbird-website pull request #257
Opened 2021-06-11 12:07 UTC by ryanleesipes

Let me know how you guys think this looks. Mission preamble and statement.

2021-06-11 18:01 UTC, Alecaddd requested changes

2021-06-11 18:01 UTC, Alecaddd commented on website/about/index.html
> +
missing the closing `</aside>` tag.

2021-06-14 12:45 UTC, ryanleesipes reviewed
Ah, good catch @Alecaddd

2021-06-14 12:46 UTC, ryanleesipes commented
I don't have the ability to merge the changes, @Sancus or @Alecaddd do you?

2021-06-14 19:00 UTC, Sancus requested changes
This patch creates a pretty wonky layout with a big white space below the group photo, and misaligned text paragraphs.

![image](https://user-images.githubusercontent.com/479671/121944858-fee7c780-cd07-11eb-8ad7-3911ceee546f.png)

We probably need to fix that before it can go live.

2021-06-14 19:00 UTC, Sancus commented on website/about/index.html
> +            {{ _('Thunderbird facilitates cross platform, decentralized, open-standard communication, which puts the user in control of their data and workflow. We aspire to offer an interoperable an
extra `)` causes build failure.

2021-06-14 19:00 UTC, Sancus commented on website/about/index.html
> +            platform for current and future forms of messaging.')) }}
extra `)` at the end causes build failure.

2023-06-20 02:32 UTC, Sancus commented
Completed in #446.

2023-06-20 02:32 UTC, closed without merging