ESR start page
thundernest/thunderbird-website pull request #318
Opened 2022-06-17 14:44 UTC by micahilbery

fixes #309 

I wasn't entirely sure what to do with the beta sections of the beta start page, so I just removed them. If we would like to add back in some release specific content I can do that as well.

![image](https://user-images.githubusercontent.com/10608836/174320509-5ec765ac-fc6d-4b70-b8a4-c2426f0b2fad.png)

2022-06-17 15:04 UTC, jfx2006 commented
Drive-by comment: "You don’t need to be an expert" is stated twice in the "Help" text.

2022-06-17 16:16 UTC, Alecaddd requested changes
What about these small copy changes?

2022-06-17 16:16 UTC, Alecaddd commented on start-page/release/index.html
> +            <p>{{ _('If Crash Reporter appeared (when Thunderbird crashes), please provide more details to help developers') }}</p>
```suggestion
            <p>{{ _('If Crash Reporter appears when Thunderbird crashes, please provide as many details as possible to help developers') }}</p>
```

2022-06-17 16:16 UTC, Alecaddd commented on start-page/release/index.html
> +              {{ _('Question? Problem?') }}
```suggestion
              {{ _('Questions? Problems?') }}
```

2022-06-17 17:19 UTC, wsmwk commented
@Alecaddd those are all great changes.

I had two requests in issue #309 - can we add these two actions under Help?  
* Share ideas and feedback -> https://connect.mozilla.org/
* Help make Thunderbird better by using beta -> https://www.thunderbird.net/download/beta/   (but something shortter than that)

2022-06-17 17:33 UTC, wsmwk commented
Other possibilities for "Help make Thunderbird better by using beta":
* Download and test Beta
* Test future features in Beta
* Explore future features in Beta

2022-06-17 21:26 UTC, Alecaddd commented
> I had two requests in issue #309 - can we add these two actions under Help?

@micahilbery can you add these?

> Help make Thunderbird better by using beta -> https://www.thunderbird.net/download/beta/   (but something shortter than that)

I'd suggest:
- Help make Thunderbird better. [Get the Beta](https://www.thunderbird.net/download/beta/)

2022-06-17 21:26 UTC, Alecaddd approved these changes
Looks good to me, with the two additions from Wayne.

2022-06-17 21:26 UTC, Alecaddd commented on start-page/release/index.html
> +            <p>{{ _('If Crash Reporter appears when Thunderbird crashes, please provide as many details as possible to help developers') }}</p>
Nit: add a period at the end of the sentence.

```suggestion
            <p>{{ _('If Crash Reporter appears when Thunderbird crashes, please provide as many details as possible to help developers.') }}</p>
```

2022-06-18 15:04 UTC, ryanleesipes reviewed
With the changes requested by Wayne and Alex, I approve. Please think carefully where these are put based on relevance to users. I think the beta appeal should go last. I think share ideas should go further up (maybe second or third). 🤷‍♂️

2022-06-18 15:15 UTC, ryanleesipes commented
I do worry the missing donation appeal (why you should donate), will negatively effect overall donations. What was the thought process behind that decision?

2022-06-18 17:28 UTC, wsmwk commented
> I do worry the missing donation appeal (why you should donate), will negatively effect overall donations. What was the thought process behind that decision?

I asked for feedback about this in #309, because in the beta start page we collectively decided to not have donation text and instead focus on the beta experience (data shows we have not been getting donations throught the beta start age).  It was not intended that we do the same for the release start page.  

17.2% of donations (number of donations, not $) come from the start page, per one week of data for the end of May that Tom shared with me.  We should be guided by annual numbers (factoring out special appeals, etc) but I don't have those at hand - my guess for annual basis is 10-15%. That's significant, and so I think we should have some text about donation. 

That said, in #309 I ask Ryan and Alex (perhaps I asked in the wrong way?) that we see frequent complaints where the user states "how do I turn off the start page because ...
a) “every day you pester me about donations” (regardless of whether I have donated),
b) “I have already donated, but you ask anyway - don’t you know that I have already donated?”

To me this suggests several things
* keep the donation widget in the top right - I don't think users will find that to be offensive
* place donation text in a section down with the other blocks - perhaps near the end?
* use wording that acknowledges/thanks those who have already donated
* in general choose wording that makes it less likely the user will want to turn off the start page
* if we do decide to have a "page header" that mentions donations, I think it should be done only in passing as part of some broader message about user engagement

2022-06-18 17:30 UTC, wsmwk commented
And also, we should attempt to measure whether our new release start page significantly changes to rate of donation.

2022-06-18 21:00 UTC, wsmwk commented
If you want, we can develop updated text using this [start page document](https://docs.google.com/document/d/1aIA9ubz7IFyy_eiHxWylTImV3eJVE6KdlsSx0vVyeTY/edit?usp=sharing). The current start page contains four paragraphs about donations. Perhaps we can reduce to two paragraphs?

2022-06-18 22:05 UTC, Sancus commented
Well, the new start page does have a larger, more prominently colored donation button. So I'm not 100% it actually will reduce donations. I'm just not sure. I think it's fine to try it the way it is now, but if we do that, we need to keep an eye on the start page sourced donations and ensure they haven't gone down significantly.

That won't be easy given the variability of donations, but hopefully a month's testing should work. Is the 17.2% number relatively consistent for every month or does it change month to month? If it's somewhat consistent we should be able to just check that that proportion doesn't go down.

2022-06-21 03:36 UTC, Alecaddd commented
Let's hold on with this for now, and schedule a quick meeting to properly define the full content of what we want on this page and approve that.

Apologies to be a party pooper, but these back and forth edits and suggestions on the PR are not the most efficient way to reach agreement on the content and move the work forward.

I'll ping you all tomorrow and we can nail this down in a quick session.

2022-06-22 17:20 UTC, micahilbery commented
![Screenshot 2022-06-22 at 12-19-12 Welcome to Thunderbird](https://user-images.githubusercontent.com/10608836/175098855-98d1b435-eecc-4369-bcb8-d26bd0ba6c3a.png)

![Screenshot 2022-06-22 at 12-19-03 Welcome to Thunderbird](https://user-images.githubusercontent.com/10608836/175098871-e2e35b0e-deaf-42a6-b1a3-b4fd26e22cb1.png)

2022-06-22 18:52 UTC, Alecaddd commented
This looks good.
@ryanleesipes what do you think?

2022-06-23 15:51 UTC, Alecaddd commented on media/css/new-start-style.css
> +  border-radius: .12rem;
Nit: border radius should be a fixed value since we don't want to change based on the font size.
Let's make it 3px.

2022-06-23 20:27 UTC, micahilbery commented on media/css/new-start-style.css
> +  padding: .25rem .75rem;
:+1: I have replaced all spacing values with `em`s

2022-06-23 20:40 UTC, micahilbery commented
This should fix #319 as well now.

2022-06-26 18:35 UTC, merged