Update donate cta in 102 What's New page
thundernest/thunderbird-website pull request #326
Opened 2022-08-15 18:44 UTC by micahilbery

2022-08-15 18:49 UTC, micahilbery commented
I would also like to remove the `site_header_nav` on this page only but I haven't found a way to do that without giving it a custom `base-resp` if anyone has any tips on how I could best go about doing that.

2022-08-15 20:14 UTC, Alecaddd commented
@micahilbery check this: https://github.com/thundernest/thunderbird-website/blob/db224551f77a09303c5b17533faa4d68cd5d6dfb/website/_includes/base-resp.html#L16

We already have some inline condition to check the type of page.
You can print out `active_page` and see what it returns and use that as condition to exclude the main nav.

Also, remember to change the UTM link in the donate button.

2022-08-15 20:53 UTC, micahilbery commented
![image](https://user-images.githubusercontent.com/10608836/184716440-25453f77-6004-4d19-956a-f415312a4b7b.png)

2022-08-15 22:54 UTC, ryanleesipes commented
The UTM link should be: https://give.thunderbird.net?utm_source=whats_new_page&utm_medium=thunderbird&utm_campaign=whats_new_102&utm_content=cta

(this is for where the donate button goes).

2022-08-15 22:56 UTC, ryanleesipes requested changes
Please add the following link to the donate button before I can approve: 

https://give.thunderbird.net?utm_source=whats_new_page&utm_medium=thunderbird&utm_campaign=whats_new_102&utm_content=cta

Also, @Alecaddd discussed potentially adjusting the donate box color. If he says we should do that, I think that might help the content stand out more. Otherwise the design looks good to me.

2022-08-16 01:02 UTC, micahilbery commented
> Please add the following link to the donate button before I can approve:
> 
> https://give.thunderbird.net?utm_source=whats_new_page&utm_medium=thunderbird&utm_campaign=whats_new_102&utm_content=cta

Currently our donate link helper function doesn't support creating a link like this. That function will need to be updated before this can happen or we will have to use a direct link which might interfere somewhere else I'm not sure.

2022-08-16 02:03 UTC, Alecaddd requested changes
Thanks for working on this so quickly.
This needs to be fixed for mobile, as the donation appeal should be center aligned when the image disappear.

2022-08-16 02:03 UTC, Alecaddd commented on website/thunderbird/102.0/whatsnew/index.html
> +    <aside class="xl:flex hidden xl:ml-8 max-w-3xl">
I think we should make it a tad smaller, by re-enabling the `max-w-2xl` and using that.

2022-08-16 02:09 UTC, ryanleesipes commented
> > Please add the following link to the donate button before I can approve:
> > 
> > https://give.thunderbird.net?utm_source=whats_new_page&utm_medium=thunderbird&utm_campaign=whats_new_102&utm_content=cta
> 
> Currently our donate link helper function doesn't support creating a link like this. That function will need to be updated before this can happen or we will have to use a direct link which might interfere somewhere else I'm not sure.
> 
> 

@Sancus can you help resolve this?

2022-08-16 16:41 UTC, Alecaddd approved these changes
This looks good for me, thanks.
As usual, @Sancus should be the final reviewer and the one to pull the trigger on merging this.

2022-08-16 19:25 UTC, ryanleesipes approved these changes

2022-08-16 19:26 UTC, ryanleesipes commented
Has my approval too. @Sancus can you do a quick review and, if it looks good, get it merged?

2022-08-16 20:31 UTC, merged