Create a newsletter landing page, and consolidate the newsletter form.
thundernest/thunderbird-website pull request #372
Opened 2023-01-23 18:42 UTC by MelissaAutumn

Resolves #371 

I've re-used the existing form, and added the "See previous newsletters" link I used on the WP side. I've also done some tweaks to ensure that the mobile view is as decent as possible. (This being a newsletter landing page and all.)

Some questions/concerns:
- Do we want the header and footer on this page, or is this more of a stand-alone page?

- I find the actual newsletter form, and the standard small-link anchour tags a bit too small for me. I feel like we could double the size without too much issue there, but it would break consistency with the rest of the site. (And the pre-footer.)

Screenshots:
Full width (1800w):
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/97147377/214121871-72899903-ae7b-4547-9ea0-1831a9dfabd6.png">

Half width (900w):
<img width="900" alt="image" src="https://user-images.githubusercontent.com/97147377/214119204-201ae5a3-22e0-4969-b1cf-0655fd144021.png">

Iphone 12 mini:
![image](https://user-images.githubusercontent.com/97147377/214119430-8df4f717-5e53-47e2-a9cd-d7a313c66bfe.png)

2023-01-23 23:00 UTC, Sancus commented
@micahilbery Hey Micah, can you take a look at this and offer any suggestions you might have design-wise?

I think we should definitely remove the pre-footer at least, and maybe the header as well. Also, the signup form should go up top of the text, be centered, and the button definitely needs to be larger. The call to action here is to sign up for the newsletter, we don't want to detract or distract from that and we want people to gravitate to doing that immediately.

@KillYourFM Any comments?

2023-01-24 07:52 UTC, KillYourFM commented
The call to action here is to sign up for the newsletter, we don't want to detract or distract from that and we want people to gravitate to doing that immediately.
> 
> @KillYourFM Any comments?

The mobile version is perfect! 
On the desktop pages, I would suggest removing the Download and Contribute links. This page should only have a single call to action to maximize signups. It's a nitpick though, and it's just my opinion.

2023-01-25 19:06 UTC, MelissaAutumn commented
Yeah I'll be knocking off the header, and pre-footer (Download and Give sections.), and making the entry field larger, as it's so tiny right now.

2023-01-26 00:17 UTC, MelissaAutumn commented
So I've played around with a few different styles, and I've attached the "good" looking ones below. I think the page could definitely benefit from having more content. 

Maybe we could add a "Check us out on these social media platforms" (but worded better...) with larger icons for each site. Additionally we could hide the social media icons in the footer for this page only. 

I've checked out a few other orgs newsletter CTA / landing pages, and they all tend to be very small, and devoid of content. 🤔 

Bigger, but more or less the same:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/97147377/214721562-c387a676-cc4d-4ea8-9ba3-1424cf766181.png">
Bigger alternate styling:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/97147377/214721759-9b123f29-d8f5-4fd4-97a7-1151166dff82.png">

Any ideas folks?

2023-01-26 04:26 UTC, KillYourFM commented
> So I've played around with a few different styles, and I've attached the "good" looking ones below. I think the page could definitely benefit from having more content.
> 
> Maybe we could add a "Check us out on these social media platforms" (but worded better...) with larger icons for each site. Additionally we could hide the social media icons in the footer for this page only.
> 
> I've checked out a few other orgs newsletter CTA / landing pages, and they all tend to be very small, and devoid of content. 🤔
> 
> Bigger alternate styling: <img alt="image" width="901" src="https://user-images.githubusercontent.com/97147377/214721759-9b123f29-d8f5-4fd4-97a7-1151166dff82.png">
> 
> Any ideas/suggestions/comments/rubber stamps folks?

This one ("bigger, alternate styling") really pops. 

Some suggestions:

1. Perhaps center the "Join Our Newsletter" heading so it center-aligns with the rest of the content. 
2. Let's keep the social icons, but move up the existing row of social icons to below the email signup box. Make them larger as you said, and extend the blue page background beneath those. Ensure that if clicked, they open in a new tab. Let's not do a separate heading or callout text for the social destinations, though. I think it would add too much noise to the intent of the page. 
3. Then start the grey background / footer area where the Thunderbird logo is now.

2023-01-26 18:11 UTC, MelissaAutumn commented
@KillYourFM (and maybe @micahilbery) How's something like..

Wide shot:
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/97147377/214913750-4b164769-4fbc-451a-85b7-4ef239f48b33.png">
Not Wide shot:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/97147377/214912382-2a7d77e2-697f-4f85-a0b9-64688a4ecf83.png">
Iphone 11 miniii:
![image](https://user-images.githubusercontent.com/97147377/214915461-23db0c54-607a-4f63-9387-d78fd21a8c49.png)
![image](https://user-images.githubusercontent.com/97147377/214915412-31ef2e06-7ef2-4197-b6d2-376ed132929e.png)
Hover interaction: (Standard, but just as refresher)
<img width="540" alt="image" src="https://user-images.githubusercontent.com/97147377/214915785-620d5ab0-9a2f-4eee-840f-9fdc96caf920.png">


I had to drop the ! off the title as, while it is centred the ! added to much visual weight and made it look not centred. 🤔 

I've been playing with a "light" theme version of the social media buttons, since the standard dark appearance against the bright blue wasn't great. But something feels off about them..

But the social media links seem to balance it out quite nicely, so it's a good step.

2023-01-27 17:55 UTC, Alecaddd commented
The white box on white input field with light grey text is not great for a11y.
Colors should be tweaked a bit. I'll suggest some edits in a bit

2023-01-27 23:29 UTC, Alecaddd requested changes
I left some comments and suggestions to improve the style and accessibility.
The final result should look like this. Some changes should also affect the look of the newsletter form used in the home page.
<img width="477" alt="Screenshot_20230127_032800" src="https://user-images.githubusercontent.com/2527103/215224894-29de49d4-7719-40b7-a6f1-504212add8aa.png">

2023-01-27 23:29 UTC, Alecaddd commented on website/newsletter/index.html
> +      <div class="flex flex-col items-center mb-20 mx-auto max-w-xl bg-grey p-4 rounded shadow-lg text-black-light no-underline md:font-md">
I would remove the box shadow and grey background from this.

2023-01-27 23:29 UTC, Alecaddd commented on website/_includes/newsletter-form.html
> +class="shadow flex items-center rounded-md self-start p-1"
for this I would use a grey-lighter background and let the child items stretch its full height.
Also maybe a 6px gap.

2023-01-27 23:29 UTC, Alecaddd commented on assets/less/components/links.less
> +  &:extend(.social-link, .font-regular, .bg-grey, .text-blue, .font-semibold, .shadow-md, .mb-4);
let's use a `text-blue-dark` for these, as well as the background color on rollover in order to guarantee AA readability.
The firefox inspector will also complaint if the AA is below 4points.

2023-01-27 23:29 UTC, Alecaddd commented on website/newsletter/index.html
> +          <a class="small-link font-regular text-blue" href="https://us12.campaign-archive.com/home/?u=f8051cc8637cf3ff79661f382&id=56428f2efc" title="View previous newsletters">{{ _('View previous n
make this `text-white`

2023-01-27 23:29 UTC, Alecaddd commented on assets/less/components/buttons.less
> +  &:extend(.w-40, .h-8, .rounded-xs, .border-none, .bg-primary-button, .text-white, .p-2, .pl-3, .pr-3, .uppercase, .font-semibold, .appearance-none);
Remove the fixed height so we let the button stretch the full height.

2023-01-27 23:29 UTC, Alecaddd commented on website/newsletter/index.html
> +        <div class="w-full">
Add a `bg-grey-light` and a 4px border radius to this.

Then the input field and button should have a 2px border radius.

2023-01-28 01:05 UTC, MelissaAutumn commented
Not wide:
![image](https://user-images.githubusercontent.com/97147377/215231387-4467b180-b96a-41ff-9aa7-e6a55c544f6f.png)

Wiiiide:
![image](https://user-images.githubusercontent.com/97147377/215232901-df9e98cc-1644-49dd-9fb6-a8a2c31e6133.png)

Mobile-ish: (Accurate to my phone)
![image](https://user-images.githubusercontent.com/97147377/215232749-a2ecd403-693d-4dd7-aea1-2eadd70089e6.png)

Adjusted Hover:
![image](https://user-images.githubusercontent.com/97147377/215232866-fb75efc7-cd22-455f-8c4b-3b41ea72d007.png)

I've done some additional mobile adjustments. How's the icon background colour on the social icons? It should probably match, huh. 

...I need to fix the white gap at the bottom

2023-01-29 16:29 UTC, micahilbery approved these changes
Looks great!

2023-01-31 08:24 UTC, merged