Features/376 replace download and donate button
thundernest/thunderbird-website pull request #377
Opened 2023-01-26 23:46 UTC by MelissaAutumn

Resolves #376 

A bit of feature creep in this one. While re-working some things, I came to conclusion that I was over-complicating the way we load the donation form. So now it just replaces the links on startup, and this fixes any silly issue we've had with scrolling, page refreshing, etc...

**Note: We will have to confirm the utm tags are working correctly after this goes on staging.** 

Now onto the main show:

Re-implemented our button, and added an animation similar to the one FRU uses. It's like the no-name version, there's no increasing pulses on hover (because css animation hates changing duration mid animation cycle.) but it works, and allows us to hopefully add utm tags. FRU seems to remove the utm tags from the url, but they appear in the javascript event details. 

I've also added my prefer-reduce-motion change, which removes the animation. This still applies the background colour change.

Before Animation:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/97147377/214975030-eabc3b9e-ec04-49fd-bac6-262659ecb035.png">
Mid Animation:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/97147377/214974118-f567faa5-416c-4bb1-8017-00ebe722a37e.png">
Hovered:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/97147377/214974180-74dff570-3341-4657-b3bd-7ca3936ad433.png">

Tested this on Firefox, Edge, Safari, Chrome.

2023-01-27 07:19 UTC, Sancus commented
Good job! I think the animation is great. However, the contents of the button need a little work. The text is quite a bit smaller than FRU's(which makes it contrast worse with the 'no thanks') and it's not vertically centered.

2023-01-27 07:20 UTC, Sancus requested changes
Good job! I think the animation is great. However, the contents of the button need a little work. The text is quite a bit smaller than FRU's(which makes it contrast worse with the 'no thanks') and it's not vertically centered.

2023-01-27 17:54 UTC, Alecaddd commented
The contrast of the hover button is also not great.
Sorry to jump in, I'm gonna add myself as a reviewer and suggest some CSS fixes

2023-01-27 18:51 UTC, Sancus commented
Yea that's a good point, the font color on hover should change like FRU's does.

2023-01-27 19:26 UTC, MelissaAutumn commented
<img width="782" alt="image" src="https://user-images.githubusercontent.com/97147377/215179307-2f2f5c81-ab2a-487f-b9b5-cdbb59c569e6.png">
<img width="703" alt="image" src="https://user-images.githubusercontent.com/97147377/215179348-b4e876ef-745a-4cdd-bca9-cd05b0f286bb.png">

Sounds good, I've adjusted positioning to match staging more closely, and lightened the alpha level of the background-colour hover effect. Let me know I should swap the background-colour hover to the same green as the text.

2023-01-27 23:02 UTC, Alecaddd approved these changes
Just a few nits, for the rest looks good.
Great work!

2023-01-27 23:07 UTC, MelissaAutumn commented on assets/less/components/donation-elements.less
>  }
I don't think we do, I'll make a note to add one in the near future.

2023-01-27 23:26 UTC, MelissaAutumn commented
Gonna have to squish these commits on merge 😅 

I've tweaked the size, positioning and animation slightly. It's faster than FRU, but not as fast as their hover speed-up. So like a happy medium?

2023-01-30 20:59 UTC, Sancus approved these changes

2023-01-30 21:00 UTC, merged